=== UO264872/SEW-F1/html-css/xml/competicion.dtd
<!ELEMENT carreras (carrera+)>
<!ELEMENT carrera (circuito,ganador,nacimiento-ganador,pais-ganador,coordenadas-nacimiento-ganador,
foto-ganador?,fecha-competicion,pais-circuito,coordenadas-circuito,videos,comentarios)>
<!ELEMENT circuito (#PCDATA)>
<!ELEMENT ganador (#PCDATA)>
<!ELEMENT nacimiento-ganador (#PCDATA)>
<!ELEMENT pais-ganador (#PCDATA)>
<!ELEMENT coordenadas-nacimiento-ganador (#PCDATA)>
<!ELEMENT foto-ganador (#PCDATA)>
<!ELEMENT fecha-competicion (#PCDATA)>
<!ELEMENT pais-circuito (#PCDATA)>
<!ELEMENT coordenadas-circuito (#PCDATA)>
<!ELEMENT videos (video,video?,video?)>
<!ELEMENT video (#PCDATA)>
<!ELEMENT comentarios (comentario*)>
<!ELEMENT comentario (#PCDATA)>

=== UO264872/SEW-F1/html-css/xml/competicion.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE carreras SYSTEM "competicion.dtd">
<carreras>
    <carrera>
        <circuito>Circuito internacional de Bahrein</circuito>
        <ganador>L.Hamilton</ganador>
        <nacimiento-ganador>1985-01-07</nacimiento-ganador>
        <pais-ganador>Gran Bretaña</pais-ganador>
        <coordenadas-nacimiento-ganador>51.902617,-0.2278547,13</coordenadas-nacimiento-ganador>
        <foto-ganador>https://soymotor.com/sites/default/files/styles/small/public/imagenes/piloto/perfil-lewis-hamilton-2022-soymotor_0.png</foto-ganador>
        <fecha-competicion>2021-03-28</fecha-competicion>
        <pais-circuito>Bahrein</pais-circuito>
        <coordenadas-circuito>26.0368368,50.508554,17</coordenadas-circuito>
        <videos>
            <video>https://www.youtube.com/watch?v=QuBlV0dixMo</video>
        </videos>
        <comentarios>
            <comentario>Gran carrera para comenzar la temporada</comentario>
            <comentario>Comienza la temporada con victoria de Hamilton</comentario>
        </comentarios>
    </carrera>
    <carrera>
        <circuito>Autodromo Enzo e Dino Ferrari</circuito>
        <ganador>M.Verstappen</ganador>
        <nacimiento-ganador>1997-09-30</nacimiento-ganador>
        <pais-ganador>Paises Bajos</pais-ganador>
        <coordenadas-nacimiento-ganador>50.9244913,5.1734629,11</coordenadas-nacimiento-ganador>
        <foto-ganador>https://cdn-8.motorsport.com/images/mgl/24vA3r46/s8/max-verstappen-red-bull-racing-1.jpg</foto-ganador>
        <fecha-competicion>2021-04-18</fecha-competicion>
        <pais-circuito>Italia</pais-circuito>
        <coordenadas-circuito>44.3440776,11.7121622,17</coordenadas-circuito>
        <videos>
            <video>https://www.youtube.com/watch?v=ds0BC8RDJ5o</video>
            <video>https://www.youtube.com/watch?v=xY1io9qtx_E</video>
        </videos>
        <comentarios>
            <comentario>Verstappen se adelanta a Hamilton en la segunda carrera del año</comentario>
        </comentarios>
    </carrera>
    <carrera>
        <circuito>Autódromo Internacional do Algarve</circuito>
        <ganador>L.Hamilton</ganador>
        <nacimiento-ganador>1985-01-07</nacimiento-ganador>
        <pais-ganador>Gran Bretaña</pais-ganador>
        <coordenadas-nacimiento-ganador>51.902617,-0.2278547,13</coordenadas-nacimiento-ganador>
        <foto-ganador>https://soymotor.com/sites/default/files/styles/small/public/imagenes/piloto/perfil-lewis-hamilton-2022-soymotor_0.png</foto-ganador>
        <fecha-competicion>2021-05-02</fecha-competicion>
        <pais-circuito>Portugal</pais-circuito>
        <coordenadas-circuito>37.2313374,-8.6305163,17</coordenadas-circuito>
        <videos>
            <video>https://www.youtube.com/watch?v=-9-8gvYantk</video>
        </videos>
        <comentarios>
            <comentario>Sigue la lucha entre Hamilton y Verstappen</comentario>
            <comentario>Hamilton le arrebata el podio a Verstappen esta vez</comentario>
            <comentario>El coche Mercedes destaca por su superioridad</comentario>
        </comentarios>
    </carrera>
    <carrera>
        <circuito>Circuit de Barcelona-Catalunya</circuito>
        <ganador>L.Hamilton</ganador>
        <nacimiento-ganador>1985-01-07</nacimiento-ganador>
        <pais-ganador>Gran Bretaña</pais-ganador>
        <coordenadas-nacimiento-ganador>51.902617,-0.2278547,13</coordenadas-nacimiento-ganador>
        <foto-ganador>https://soymotor.com/sites/default/files/styles/small/public/imagenes/piloto/perfil-lewis-hamilton-2022-soymotor_0.png</foto-ganador>
        <fecha-competicion>2021-05-09</fecha-competicion>
        <pais-circuito>España</pais-circuito>
        <coordenadas-circuito>41.5684877,2.2551125,17</coordenadas-circuito>
        <videos>
            <video>https://www.youtube.com/watch?v=HuLdJLB6sBo</video>
            <video>https://www.youtube.com/watch?v=-r89PNKDYY8</video>
            <video>https://www.youtube.com/watch?v=s4crWWSC-aU</video>
        </videos>
        <comentarios>
            <comentario>Se repite la misma historia que en las carreras previas</comentario>
            <comentario>Bottas no consigue sacarle el rendimiento esperado al coche</comentario>
        </comentarios>
    </carrera>
    <carrera>
        <circuito>Circuito de Mónaco</circuito>
        <ganador>M.Verstappen</ganador>
        <nacimiento-ganador>1997-09-30</nacimiento-ganador>
        <pais-ganador>Paises Bajos</pais-ganador>
        <coordenadas-nacimiento-ganador>50.9244913,5.1734629,11</coordenadas-nacimiento-ganador>
        <foto-ganador>https://cdn-8.motorsport.com/images/mgl/24vA3r46/s8/max-verstappen-red-bull-racing-1.jpg</foto-ganador>
        <fecha-competicion>2021-05-23</fecha-competicion>
        <pais-circuito>Mónaco</pais-circuito>
        <coordenadas-circuito>44.422333,-4.2436169,6</coordenadas-circuito>
        <videos>
            <video>https://www.youtube.com/watch?v=GK5qm8AZ1dQ</video>
        </videos>
        <comentarios>
            <comentario>Verstappen supera otra vez a Hamilton</comentario>
            <comentario>Hamilton cae a la 7º posición, lo que da ventaja a Verstappen</comentario>
            <comentario>El mundial comienza a ponerse reñido</comentario>
            <comentario>El español Carlos Sainz consigue el primer podio de la temporada</comentario>
        </comentarios>
    </carrera>
    <carrera>
        <circuito>Circuito callejero de Bakú</circuito>
        <ganador>S.Perez</ganador>
        <nacimiento-ganador>1990-01-26</nacimiento-ganador>
        <pais-ganador>Mexico</pais-ganador>
        <coordenadas-nacimiento-ganador>40.6321849,-3.2081919,13</coordenadas-nacimiento-ganador>
        <foto-ganador>https://cdn-5.motorsport.com/images/mgl/0a9neZP0/s8/sergio-perez-red-bull-racing-1.jpg</foto-ganador>
        <fecha-competicion>2021-06-06</fecha-competicion>
        <pais-circuito>Azerbaiyan</pais-circuito>
        <coordenadas-circuito>40.3729222,49.8509929,17</coordenadas-circuito>
        <videos>
            <video>https://www.youtube.com/watch?v=suZHkUxPzjE</video>
            <video>https://www.youtube.com/watch?v=GqLRwtyjpUY</video>
        </videos>
        <comentarios>
            <comentario>Ni Verstappen ni Hamilton consiguen hacer podio</comentario>
            <comentario>S.Perez consigue su primera victoria de la temporada</comentario>
            <comentario>Alpha tauri y Aston Martin consiguen hacer podio por primera vez en la temporada</comentario>
        </comentarios>
    </carrera>
    <carrera>
        <circuito>Circuito Paul Ricard</circuito>
        <ganador>M.Verstappen</ganador>
        <nacimiento-ganador>1997-09-30</nacimiento-ganador>
        <pais-ganador>Paises Bajos</pais-ganador>
        <coordenadas-nacimiento-ganador>50.9244913,5.1734629,11</coordenadas-nacimiento-ganador>
        <foto-ganador>https://cdn-8.motorsport.com/images/mgl/24vA3r46/s8/max-verstappen-red-bull-racing-1.jpg</foto-ganador>
        <fecha-competicion>2021-06-20</fecha-competicion>
        <pais-circuito>Francia</pais-circuito>
        <coordenadas-circuito>43.2490101,5.7861183,17</coordenadas-circuito>
        <videos>
            <video>https://www.youtube.com/watch?v=5hBwgJtMxLM</video>
        </videos>
        <comentarios>
            <comentario>Verstappen y Hamilton consiguen volver al podio como es habitual</comentario>
            <comentario>Bottas sigue sin sacar rendimiento al coche</comentario>
            <comentario>RedBull pisa fuerte en el campeonato de constructores con el podio de Perez</comentario>
        </comentarios>
    </carrera>
    <carrera>
        <circuito>Red Bull Ring</circuito>
        <ganador>M.Verstappen</ganador>
        <nacimiento-ganador>1997-09-30</nacimiento-ganador>
        <pais-ganador>Paises Bajos</pais-ganador>
        <coordenadas-nacimiento-ganador>50.9244913,5.1734629,11</coordenadas-nacimiento-ganador>
        <foto-ganador>https://cdn-8.motorsport.com/images/mgl/24vA3r46/s8/max-verstappen-red-bull-racing-1.jpg</foto-ganador>
        <fecha-competicion>2021-06-27</fecha-competicion>
        <pais-circuito>Austria</pais-circuito>
        <coordenadas-circuito>47.2201846,14.7629977,17</coordenadas-circuito>
        <videos>
            <video>https://www.youtube.com/watch?v=LxLVqf5OtIE</video>
        </videos>
        <comentarios>
            <comentario>Se repite el mismo escenario de la carrera anterior</comentario>
            <comentario>Bottas consigue mejorar los resultados y vuelve a conseguir el podio</comentario>
            <comentario>Cada vez se aprieta más el mundial de constructores con los podios intermitentes de sus pilotos</comentario>
        </comentarios>
    </carrera>
    <carrera>
        <circuito>Red Bull Ring</circuito>
        <ganador>M.Verstappen</ganador>
        <nacimiento-ganador>1997-09-30</nacimiento-ganador>
        <pais-ganador>Paises Bajos</pais-ganador>
        <coordenadas-nacimiento-ganador>50.9244913,5.1734629,11</coordenadas-nacimiento-ganador>
        <foto-ganador>https://cdn-8.motorsport.com/images/mgl/24vA3r46/s8/max-verstappen-red-bull-racing-1.jpg</foto-ganador>
        <fecha-competicion>2021-07-04</fecha-competicion>
        <pais-circuito>Austria</pais-circuito>
        <coordenadas-circuito>47.2201846,14.7629977,17</coordenadas-circuito>
        <videos>
            <video>https://www.youtube.com/watch?v=a2kkuQS_gXk</video>
        </videos>
        <comentarios>
            <comentario>Verstappen consigue su tercera victoria consecutiva</comentario>
            <comentario>Hamilton cae del podio a la 4º posición</comentario>
            <comentario>Bottas consigue la segunda posicion</comentario>
            <comentario>Norris consigue su primer podio de la temporada con la tercera posicion</comentario>
        </comentarios>
    </carrera>
    <carrera>
        <circuito>Circuito de Silverstone</circuito>
        <ganador>L.Hamilton</ganador>
